"""Character vocabulary for the transformer (spec 5.2).

Plain ``stoi``/``itos`` dicts producing ``input_ids`` directly.  No HuggingFace
tokenizer: fighting ``PreTrainedTokenizer`` for a ~48-symbol character
vocabulary is a guaranteed time sink and buys nothing here.

Sequence layout::

    <bos> caption_text <sep> grid(110 chars) <eos> <pad>...

The grid occupies exactly 110 characters (10 rows of 10 tiles, each row
newline-terminated), which is what makes the constrained decoder's position
bookkeeping trivial.

Sequence length
---------------
The spec suggested ``max_length = 160``, which fits its four-field example
caption (``"hard, ~40 moves, dense walls, corridors"``, 38 chars).  The feature
table specifies **five** features, and the conditioning vector encodes five, so
we keep all five and the longest caption is 65 characters:
``1 + 65 + 1 + 110 + 1 = 178``.  ``MAX_LEN`` is therefore 178, not 160.
Truncating captions instead would silently corrupt the conditioning signal,
which is the thing being measured.
"""

from __future__ import annotations

from typing import Dict, List, Sequence

from .boxoban import GRID_STR_LEN

PAD = "<pad>"
BOS = "<bos>"
SEP = "<sep>"
EOS = "<eos>"
SPECIALS = (PAD, BOS, SEP, EOS)

# Grid tiles plus the row terminator.
GRID_CHARS = ("#", "@", "$", ".", " ", "\n")
# Caption alphabet: lowercase letters, digits, comma, tilde, space.
CAPTION_CHARS = tuple("abcdefghijklmnopqrstuvwxyz0123456789,~ ")

_CHARS = sorted(set(GRID_CHARS) | set(CAPTION_CHARS))

itos: List[str] = list(SPECIALS) + _CHARS
stoi: Dict[str, int] = {s: i for i, s in enumerate(itos)}

PAD_ID = stoi[PAD]
BOS_ID = stoi[BOS]
SEP_ID = stoi[SEP]
EOS_ID = stoi[EOS]

VOCAB_SIZE = len(itos)

# Ids used by the constrained decoder's masking rules.
WALL_ID = stoi["#"]
FLOOR_ID = stoi[" "]
BOX_ID = stoi["$"]
GOAL_ID = stoi["."]
PLAYER_ID = stoi["@"]
NEWLINE_ID = stoi["\n"]

TILE_IDS = (WALL_ID, FLOOR_ID, BOX_ID, GOAL_ID, PLAYER_ID)

# Derived from the caption grammar rather than hardcoded, so the two cannot
# drift apart: 1 (<bos>) + longest caption + 1 (<sep>) + 110 (grid) + 1 (<eos>).
from .captions import max_caption_length as _max_caption_length  # noqa: E402

MAX_CAPTION_LEN = _max_caption_length()             # 65
MAX_LEN = 1 + MAX_CAPTION_LEN + 1 + GRID_STR_LEN + 1  # 178


def encode_text(text: str) -> List[int]:
    try:
        return [stoi[c] for c in text]
    except KeyError as exc:  # pragma: no cover - captions are generated by us
        raise ValueError(f"character {exc.args[0]!r} is outside the vocabulary") from exc


def decode_ids(ids: Sequence[int], stop_at_eos: bool = True) -> str:
    out = []
    for i in ids:
        tok = itos[i]
        if tok == EOS and stop_at_eos:
            break
        if tok in SPECIALS:
            continue
        out.append(tok)
    return "".join(out)


def encode_example(caption: str, grid: str) -> List[int]:
    """Full training sequence for one (caption, grid) pair (unpadded)."""
    if len(grid) != GRID_STR_LEN:
        raise ValueError(f"grid must be {GRID_STR_LEN} chars, got {len(grid)}")
    return ([BOS_ID] + encode_text(caption) + [SEP_ID]
            + encode_text(grid) + [EOS_ID])


def encode_prompt(caption: str) -> List[int]:
    """Prefix used at generation time: ``<bos> caption <sep>``."""
    return [BOS_ID] + encode_text(caption) + [SEP_ID]


def pad_to(ids: Sequence[int], length: int = MAX_LEN) -> List[int]:
    if len(ids) > length:
        raise ValueError(f"sequence of {len(ids)} exceeds max length {length}")
    return list(ids) + [PAD_ID] * (length - len(ids))


def grid_from_ids(ids: Sequence[int]) -> str:
    """Extract the grid that follows ``<sep>``, as a raw string.

    Does not validate: callers check structural validity separately, because
    "did the model produce a well-formed grid?" is itself a reported metric.
    """
    try:
        start = list(ids).index(SEP_ID) + 1
    except ValueError:
        return ""
    out = []
    for i in ids[start:]:
        tok = itos[i]
        if tok in SPECIALS:
            break
        out.append(tok)
    return "".join(out)
