"""Rule-based baseline: a non-learned structured competitor (spec 9.1).

Random interior walls, but with two pieces of domain knowledge the random
baseline lacks:

1. a **connectivity check** -- the floor must form a single connected region,
   which is also true of every real Boxoban level (verified in Phase 3);
2. boxes and goals are placed only on **live squares**, i.e. cells from which a
   box can still reach some goal under the solver's own relaxation.  That rules
   out the single most common way a random level dies: a box in a non-goal
   corner.

This is the honest "how far does hand-written domain knowledge get you?"
competitor for the learned models.

Measured outcome (100-level samples, solver-verified)
------------------------------------------------------
At the training-median density this baseline is solvable **~1%** of the time,
against ~20% for the wall-free open room.  Two things were checked before
accepting that number:

* It is not an unsound prune.  Re-solving with deadlock pruning disabled and a
  10x node cap gives an identical verdict on every level.
* It is not caused by *starting* in a deadlock.  Additionally rejecting start
  states that fail the freeze test changes the solve rate by under one point,
  because these levels die after the first push rather than before it.

Interior walls are what kills it: at ~50% density the floor is a maze of narrow
corridors, and a box pushed into one freezes against the walls.  The open room
scores far better precisely because it has no interior walls to freeze against.
Real Boxoban levels reach ~100% solvability at the same wall density only
because they are generated by *reverse play* from an already-solved state,
which is a fundamentally different construction than sampling walls and then
dropping boxes on them.
"""

from __future__ import annotations

import random
from typing import List, Optional

from ..data.boxoban import N_BOX, N_GOAL
from ..solver.deadlock import dead_squares
from ..solver.grid import STEP, bit, cells
from .common import INTERIOR, render

TRAIN_MEDIAN_DENSITY = 0.5
MAX_ATTEMPTS = 200


def _floor_is_connected(wall_mask: int) -> bool:
    floor = [i for i in range(100) if not (wall_mask >> i) & 1]
    if not floor:
        return False
    seen = {floor[0]}
    stack = [floor[0]]
    while stack:
        cur = stack.pop()
        for d in range(4):
            n = STEP[cur][d]
            if n >= 0 and n not in seen and not (wall_mask >> n) & 1:
                seen.add(n)
                stack.append(n)
    return len(seen) == len(floor)


def _border_wall_mask() -> int:
    mask = 0
    for i in range(100):
        r, c = divmod(i, 10)
        if r in (0, 9) or c in (0, 9):
            mask |= bit(i)
    return mask


BORDER_MASK = _border_wall_mask()


def generate_one(rng: random.Random,
                 density: float = TRAIN_MEDIAN_DENSITY) -> Optional[str]:
    """One level, or ``None`` if the attempt budget ran out."""
    for _ in range(MAX_ATTEMPTS):
        n_walls = int(round(density * len(INTERIOR)))
        interior_walls = rng.sample(INTERIOR, min(n_walls, len(INTERIOR) - 12))
        wall_mask = BORDER_MASK
        for i in interior_walls:
            wall_mask |= bit(i)

        if not _floor_is_connected(wall_mask):
            continue

        free = [i for i in INTERIOR if not (wall_mask >> i) & 1]
        if len(free) < 9:
            continue

        # Goals first: "live" is defined relative to where the goals are.
        goals = rng.sample(free, N_GOAL)
        goal_mask = 0
        for g in goals:
            goal_mask |= bit(g)

        dead = dead_squares(wall_mask, goal_mask)
        live = [i for i in free if i not in set(goals) and not (dead >> i) & 1]
        if len(live) < N_BOX + 1:
            continue

        picks = rng.sample(live, N_BOX + 1)
        boxes, player = picks[:N_BOX], picks[N_BOX]
        return render(interior_walls, player, boxes, goals)
    return None


def generate(n: int, seed: int = 1337,
             density: float = TRAIN_MEDIAN_DENSITY) -> List[str]:
    rng = random.Random(seed)
    out: List[str] = []
    while len(out) < n:
        g = generate_one(rng, density)
        if g is not None:
            out.append(g)
    return out
